# ~/.tmuxinator/default.yml

name: default

# Optional tmux socket
# socket_name: foo

# Runs before everything. Use it to start daemons etc.
# pre: sudo /etc/rc.d/mysqld start

# Runs in each window and pane before window/pane specific commands. Useful for setting up interpreter versions.
# pre_window: rbenv shell 2.0.0-p247

# Pass command line options to tmux. Useful for specifying a different tmux.conf.
# tmux_options: -f ~/.tmux.mac.conf

# Change the command to call tmux.  This can be used by derivatives/wrappers like byobu.
# tmux_command: byobu

# Specifies (by name or index) which window will be selected on project startup. If not set, the first window is used.
# startup_window: logs

# Controls whether the tmux session should be attached to automatically. Defaults to true.
# attach: false

# Runs after everything. Use it to attach to tmux with custom options etc.
# post: tmux -CC attach -t default
post: tmux select-window -t default:1 && tmux attach -t default

windows:
  - terminal:
      layout: 98ad,135x44,0,0[135x31,0,0{90x31,0,0,1,44x31,91,0[44x8,91,0,2,44x22,91,9,3]},135x13,0,32,4]
      panes:
        - cd ~ && clear
        - tmux clock -t default:1.2
        - mc
        - htop
  - editor:
      layout: 68f2,134x43,0,0[135x36,0,0{89x36,0,0,2,45x36,90,0,3},135x7,0,37,4]
      panes:
        - vi
        - mc
        - cd ~/tmp && clear
